version: '3.7'

services:

 app:
  build:
   context: .
   dockerfile: Dockerfile
  image: app:1.0
  container_name: app
  command: >
    sh -c "npm run sequelize db:migrate &&
           npm start"
  volumes: 
   - app-data:/data/app
  depends_on: 
   - mysql
  env_file:
   - .env
  ports: 
   - 3000:3000
 mysql:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  volumes: 
    - mysql-data:/data/db
  environment:
    MYSQL_ROOT_PASSWORD: root123
    MYSQL_DATABASE: test_bibit
  ports: 
   - 3306:3306

volumes: 
    mysql-data:
    app-data: